on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10


name: Upload Release Asset

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    needs: [release]
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        debian-release: [testing, stable, sid]
        revision: ["3or4"]
        board: [pi]
        include:
          - board: jetson-nano
            revision: 300
            experimental: true
          - debian-release: stable
            experimental: false
          - debian-release: testing
            experimental: true
          - debian-release: sid
            experimental: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project # This would actually build your project, using zip for an example artifact
        id: build
        env:
          RELEASE: ${{ matrix.debian-release }}
          REVISON: ${{ matrix.revision }}
          BOARD: ${{ matrix.board }}
          GRAPHICAL: false
          CI: true
        run: |
          echo "deb http://us.archive.ubuntu.com/ubuntu/ groovy main restricted universe
          deb-src http://us.archive.ubuntu.com/ubuntu/ groovy main restricted universe
          " | sudo tee -a "/etc/apt/sources.list.d/groovy.list"

          echo "# Never prefer packages from groovy
          Package: *
          Pin: release n=groovy
          Pin-Priority: 1

          Package: qemu-user-static qemu
          Pin: release n=groovy
          Pin-Priority: 500" | sudo tee -a "/etc/apt/preferences.d/99-groovy"
          sudo apt update
          sudo apt install qemu gparted debootstrap qemu-user-static qemu-utils schroot debian-keyring debian-archive-keyring
          bash -x ./build.sh
          zip debian-${{ matrix.board }}-${{ matrix.revision }}-${{ matrix.debian-release }}.zip debian-${{ matrix.board }}.img
      - name: Start SSH via Ngrok
        id: ngrok
        if: ${{ failure() }}
        run: curl -sL https://gist.githubusercontent.com/ClashTheBunny/ac7ca189e1f8ab9eb5686662412a4cce/raw/7099b9db76729dc5761da72aa8525f632d8875c9/debug-github-actions.sh | bash
        env:
          # After sign up on the https://ngrok.com/
          # You can find this token here: https://dashboard.ngrok.com/get-started/setup
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}

          # This password you will use when authorizing via SSH
          USER_PASS: ${{ secrets.USER_PASS }}
      - name: Sleep 1 hour
        if: ${{ failure() }}
        run: sleep 1h
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ./debian-${{ matrix.board }}-${{ matrix.revision }}-${{ matrix.debian-release }}.zip
          asset_name: debian-${{ matrix.board }}-${{ matrix.revision }}-${{ matrix.debian-release }}.zip
          asset_content_type: application/zip
